on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:
    name: .NET

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: UnitTest
      run: dotnet test --no-build .\tests\PortalGenius.UnitTests\PortalGenius.UnitTests.csproj
    - name: IntegrationTest
      run: dotnet test --no-build .\tests\PortalGenius.IntegrationTests\PortalGenius.IntegrationTests.csproj
